### ISSUE TITLE
Problems with the interface in high resolution

### ISSUE THREAD

**Issue by ewilded** [Quitten/Autorize#10]
I noticed that when using Autorize in high resolution (like 4k), the entire configuration interface elements overlap each other, rendering it useless. 
![autorize](https://cloud.githubusercontent.com/assets/1158719/19076696/28e365e0-8a4a-11e6-9e42-349c6e32fcaa.png)
Please see the screenshot.

**Comment by Quitten** [comment]
Hi Julian,
Thank you for reporting this problem, however due to a lack of time I will not be able to fix this in the near future. Possibly my partner, Federico will be able to take care of it.
In any case, if you would like you could fix the relevant code parts yourself and send the pull request I will gladly accept it.
Let me know whether you prefer to wait or to fix it yourself,
Kind regards,
Barak

**Comment by ewilded** [comment]
To be honest I prefer to wait (:D), especially as I am terrible at Java and UI... Nonetheless I think I can give it a try. I have already achieved some improvement, will try to make everything look fine - then I will test in low resolution and make a pull request.
Regards, Julian

**Comment by Quitten** [comment]
You can give a try and i will perform tests on the pull request

**Comment by ewilded** [comment]
Allright, here it is https://github.com/ewilded/Autorize/commit/3c51397aa8a6d8adf08dfa5cbf29fb343f5f07d8#diff-370c88cf0195bbc74583252c05ef49bc.
Does not look so bad under my 4k now, however I am not sure if I did not break low resolutions in turn ;) Anyway, the root cause was using absolute positions and sizes instead of features offered by layouts.
If you are fine with my changes, please let me know, I will create a pull request.
Regards,
Julian

**Comment by ewilded** [comment]
Ok, before you actually make a pull request - I just noticed that somehow my changes broke the automatic interception (with the default 'in scope' filter), so far I have no idea how. I will let you know as soon as it's fixed. 
Thanks, Julian

**Comment by Quitten** [comment]
Ok, waiting for the pull request.

**Comment by Quitten** [comment]
Hi Julian,
i just tested your code and i saw that it changed the entire UI of the plugin, i would like to solve the resolution problem without changing the UI itself, i thought about checking the monitor resolution in the first initialization then adjust the buttons for it.
In case you can do that it will be great, because i dont want to change the plugin's UI.

**Comment by ldionmarcil** [comment]
Ran into this today, made the extension quite unusable. Because all the Java GUI components are hard coded, there is no easy way to fix this. I spent some time rewriting the indices to make things a little more readable. Forked this because its not a systemic fix, but a very dirty workaround. 
Before:
![image](https://github.com/Quitten/Autorize/assets/1320868/1aca4e4e-8b71-4a78-87d7-69ef4260aaab)
After:
![image](https://github.com/Quitten/Autorize/assets/1320868/6697e0de-7be0-495c-aaba-3cbb6676c846)


see https://github.com/ldionmarcil/Autorize/commit/e85d88400ca5824d87751edd76e8c04037072b42

**Comment by Quitten** [comment]
Hey @ewilded @ldionmarcil,
After 8 years :D, I found few weekends to implement GroupLayout on all panels (see commit 7856089), so this should be fixed now :)
Please let me know if it is fixed the resolution issue, so Ill close this issue.

**Comment by Quitten** [comment]
Hey @ewilded @ldionmarcil,
After 8 years :D, I found few weekends to implement GroupLayout on all panels (see commit 7856089), so this should be fixed now :)
Please let me know if it is fixed the resolution issue, so Ill close this issue.

**Comment by Quitten** [comment]
Hey @ewilded @ldionmarcil,
After 8 years :D, I found few weekends to implement GroupLayout on all panels (see commit 7856089), so this should be fixed now :)
Please let me know if it is fixed the resolution issue, so Ill close this issue.

**Comment by Quitten** [comment]
Hey @ewilded @ldionmarcil,
After 8 years :D, I found few weekends to implement GroupLayout on all panels (see commit 7856089), so this should be fixed now :)
Please let me know if it is fixed the resolution issue, so Ill close this issue.

**Comment by Quitten** [comment]
OK, so after 8 years, happy to say: closed.
