### ISSUE TITLE
Repeat requests without redoing all clicks

### ISSUE THREAD

**Issue by MrR10T** [Quitten/Autorize#73]

**Comment by AlbysProject** [comment]
Good morning,
It would be nice to implement a function in order to repeat all the clicks made without having to do them by hand all over again. In my case I am testing a large application and as I exclude some false positives I exclude them from the scope. Next I would like to repeat all the requests made without having to click all over again, in order to see the effect of having excluded some API or PATH from the scope. Is it possible in your opinion?
Thanks

**Comment by jaikishantulswani** [comment]
@AlbysProject It is good to check all the request with one click.

**Comment by AlbysProject** [comment]
Yes, but If I remove a request from the scope and I click on "retest selected request" I keep seeing that request as if that is in the scope. Even if I added the filter "Interception filter -> Scope Item Only"

**Comment by Quitten** [comment]
@AlbysProject - I would like to get some clarifications on your comments and request for enhancements:
* You would like to have the ability to retest all requests inside the Autorize table, is that correct?
* You think retest selected requests should go through the interception filters and be ignored in case the filters match, in case this is the case, I would like to hear more opinions on that because I am not sure this is logical. The interception filters are filtering the requests intercepted by the proxy, and not by Autorize. While retesting a selected request, there are no requests going though the proxy, it is directly sent into Autorize.

Let me know what do you think, and thanks for the feedback :) I am always glad to help the AppSec community!

**Comment by AlbysProject** [comment]
Thank you for giving me an answer in such a short time.

About the first point, yes. I would like to retest all request inside Autorize without clicking each one of them.

For the second point, would be nice to apply the interception filters even to retested request inside Autorize. Or maybe would be nice to have a different filter applicable to the request that are already inside Autorize, without passing through Proxy again.

For example:
1) I activate Autorize
2) I start clicking every path, API etc etc until i'm 100% sure that I got everything.
3) Then I try to put out of scope some requests
4) I retest all Autorize request that now get filtered directly within Autorize.

I hope the example make it more clear.

Have a nice day 😄

**Comment by Quitten** [comment]
@MrR10T  - 8a2ffad1ef0726aa9ab93377b8d88e452e6ebf37 implements the "retest all requests" feature and fixed a bug while retesting a single request, the interception filters will be taking place while retesting is performed.

Note that you will retest only the visible rows inside the table, means in case you clicked the "Clear List" button, only the new rows that will be added will be re-tested.

Hope this satisfy your needs, let me know if you have any issues or further requests.

Closing this issue for now.

Have a great day :)
