### ISSUE TITLE
Interception filter on HTTP headers

### ISSUE THREAD

**Issue by ldionmarcil** [Quitten/Autorize#88]
Hi, is there a way to intercept only requests that have a specific header? My use case is I want to replace the "Authorize" header for requests, but I don't want to pollute the request list with requests that do not have that header. I noticed there are a lot of interception filter options, but none for "Matches header" or something similar.

Thanks

**Comment by Quitten** [comment]
You are able to use `Header contains` filters to do that since I pushed https://github.com/Quitten/Autorize/commit/c32c18e3d876ec4acbb06c5daa326e45d81a65e4
Please clone Autorize and load it locally, the BAppstore version is not up to date yet.

![image](https://user-images.githubusercontent.com/8288210/171370844-8d0b298d-1d06-49b4-a272-56156774982c.png)
